apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-deployment
  labels:
    app: ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms
  template:
    metadata:
      labels:
        app: ms
    spec:
      containers:
      - env:
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: ""
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://mongoadmin:secret@mongo-service:27017/deltaStateGovtNg?authSource=admin&ssl=false
        name: springboot
        image: cendevops/election-registration:latest
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
          requests:
            cpu: "250m"
            memory: "250Mi"
